# Preload wallpapers (optional in new syntax, but recommended for speed)
wallpaper {
    monitor = eDP-1
    path = ~/Pictures/wallpapers/space-minimal.webp
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/wallpapers/saturn_retrowave.jpg
    fit_mode = cover
}

splash = false
