hl.on("hyprland.start", function()
	hl.exec_cmd("swaync")
	hl.exec_cmd("ashell")
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("blueman-applet")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("hyprlauncher -d")
	hl.exec_cmd("gammastep")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("hyprctl setcursor BreezeX-RosePine-Linux 24")

	hl.exec_cmd("[workspace 1 silent] " .. _G.browser)
	hl.exec_cmd("[workspace 2 silent] " .. _G.terminal)
	hl.exec_cmd("[workspace 3 silent] " .. _G.browser)
end)
