-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--##################

--## KEYBINDINGS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

local mainMod = "SUPER"
local mainModShift = "SUPER + SHIFT"

local menu = _G.menu
local terminal = _G.terminal
local browser = _G.browser
local fileManager = _G.fileManager
local powerManager = _G.powerManager

-- Just for master layout

hl.bind(mainMod .. " + " .. "Space", hl.dsp.layout("swapwithmaster"))

hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(menu))

hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd(powerManager))

hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + S", hl.dsp.window.float())

hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mainModShift .. " + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind("F11", hl.dsp.window.fullscreen())

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))

-- Move between monitors

hl.bind(mainModShift .. " + K", hl.dsp.window.move({ monitor = "+1" }))
hl.bind(mainModShift .. " + J", hl.dsp.window.move({ monitor = "-1" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + Next", hl.dsp.focus({ workspace = "r+1" }))
hl.bind(mainMod .. " + Prior", hl.dsp.focus({ workspace = "r-1" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = "prev" }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainModShift .. " + Next", hl.dsp.window.move({ workspace = "r+1" }))
hl.bind(mainModShift .. " + Prior", hl.dsp.window.move({ workspace = "r-1" }))
hl.bind(mainModShift .. " + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainModShift .. " + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainModShift .. " + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainModShift .. " + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainModShift .. " + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainModShift .. " + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainModShift .. " + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainModShift .. " + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainModShift .. " + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainModShift .. " + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + Tab", hl.dsp.layout("cyclenext"))

hl.bind("Print", hl.dsp.exec_cmd("hyprshot --clipboard-only -m region"))
hl.bind("SHIFT" .. " + Print", hl.dsp.exec_cmd("hyprshot -m window"))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 5%+"), { locked = true })
hl.bind(
	"XF86MonBrightnessDown",
	hl.dsp.exec_cmd(
		[[bash -c 'val=$(brightnessctl g); max=$(brightnessctl m); step=$((max/20)); min=$step; new=$((val-step)); [ $new -lt $min ] && new=$min; brightnessctl s $new']]
	),
	{ locked = true }
)

-- Limit it to 10%

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
