-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

-- -@module 'hl'

_G.terminal = "kitty"
_G.fileManager = "thunar"
_G.browser = "brave"
_G.powerManager = "wlogout"
_G.menu = "vicinae toggle"

_G.mainMonitor = "eDP-1"
_G.secondaryMonitor = "HDMI-A-1"

-- See https://wiki.hyprland.org/Configuring/Environment-variables/
