plugin {
  hyprscrolling {
    fullscreen_on_one_column = true
      column_width = 0.7
  }
  hyprexpo {
    columns = 2
      gap_size = 5
      bg_col = rgb(111111)
      workspace_method = center current # This is the key change
  }
}

