-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Bind workspaces 1-5 to DP-1

hl.workspace_rule({
	workspace = 1,
	monitor = _G.mainMonitor,
	persistent = true,
})

hl.workspace_rule({
	workspace = 2,
	monitor = _G.mainMonitor,
	persistent = true,
})

hl.workspace_rule({
	workspace = 3,
	monitor = _G.mainMonitor,
	persistent = true,
})

hl.workspace_rule({
	workspace = 4,
	monitor = _G.mainMonitor,
	persistent = true,
})

hl.workspace_rule({
	workspace = 5,
	monitor = _G.mainMonitor,
	persistent = true,
})

-- Bind workspaces 6-10 to HDMI-A-1

hl.workspace_rule({
	workspace = 6,
	monitor = _G.secondaryMonitor,
	persistent = false,
})

hl.workspace_rule({
	workspace = 7,
	monitor = _G.secondaryMonitor,
	persistent = false,
})

hl.workspace_rule({
	workspace = 8,
	monitor = _G.secondaryMonitor,
	persistent = false,
})

hl.workspace_rule({
	workspace = 9,
	monitor = _G.secondaryMonitor,
	persistent = false,
})

hl.workspace_rule({
	workspace = 10,
	monitor = _G.secondaryMonitor,
	persistent = false,
})

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

-- Core behavior

hl.window_rule({
	name = "suppressevent_maximi",
	match = {
		class = ".*",
	},
	suppress_event = "maximize",
})

-- Optional XWayland fix (only if needed)

hl.window_rule({
	name = "nofocus",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},
	no_focus = true,
})

-- Dialogs

hl.window_rule({
	name = "float",
	match = {
		title = "^(Open|Save|Save As|Choose File|File Upload)$",
	},
	float = true,
})

hl.window_rule({
	name = "center",
	match = {
		title = "^(Open|Save|Save As|Choose File|File Upload)$",
	},
	center = true,
})

hl.window_rule({
	name = "float",
	match = {
		class = "^(xdg-desktop-portal-gtk)$",
	},
	float = true,
})

hl.window_rule({
	name = "size_800_600",
	match = {
		class = "^(xdg-desktop-portal-gtk)$",
	},
	size = "800 600",
})

hl.window_rule({
	name = "center",
	match = {
		class = "^(xdg-desktop-portal-gtk)$",
	},
	center = true,
})

-- System apps

hl.window_rule({
	name = "float",
	match = {
		class = "^(pavucontrol|blueman-manager|nm-connection-editor|atril)$",
	},
	float = true,
})

hl.window_rule({
	name = "size_800_600",
	match = {
		class = "^(pavucontrol|blueman-manager|nm-connection-editor|atril)$",
	},
	size = "800 600",
})

hl.window_rule({
	name = "center",
	match = {
		class = "^(pavucontrol|blueman-manager|nm-connection-editor)$",
	},
	center = true,
})

hl.layer_rule({
	match = {
		namespace = "rofi",
	},
	blur = true,
	animation = "popin",
})

-- Ref https://wimonitor:ki.hyprland.org/Configuring/Workspace-Rules/

-- "Smart gaps" /monitor: "No gaps when only"

-- uncomment all if you wish to use that.

-- workspace = w[tv1], gapsout:10, gapsin:5

-- workspace = f[1], gapsout:0, gapsin:0

-- windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]

-- windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]

-- windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]

-- windowrulev2 = rounding 0, floating:0, onworkspace:f[1]

-- windowrulev2 = size 600 200,floating:1
