# Bind workspaces 1-5 to DP-1
workspace = 1, monitor:$mainMonitor, persistent:true
workspace = 2, monitor:$mainMonitor, persistent:true
workspace = 3, monitor:$mainMonitor, persistent:true
workspace = 4, monitor:$mainMonitor, persistent:true
workspace = 5, monitor:$mainMonitor, persistent:true

# Bind workspaces 6-10 to HDMI-A-1
workspace = 6, monitor:$secondaryMonitor, persistent:true
workspace = 7, monitor:$secondaryMonitor, persistent:true
workspace = 8, monitor:$secondaryMonitor, persistent:true
workspace = 9, monitor:$secondaryMonitor, persistent:true
workspace = 10, monitor:$secondaryMonitor, persistent:true

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
# Core behavior
windowrulev2 = suppressevent maximize, class:.*

# Optional XWayland fix (only if needed)
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Dialogs
windowrulev2 = float, title:^(Open|Save|Save As|Choose File|File Upload)$
windowrulev2 = center, title:^(Open|Save|Save As|Choose File|File Upload)$

# System apps
windowrulev2 = float, class:^(pavucontrol|blueman-manager|nm-connection-editor)$
windowrulev2 = size 800 600, class:^(pavucontrol|blueman-manager|nm-connection-editor)$
windowrulev2 = center, class:^(pavucontrol|blueman-manager|nm-connection-editor)$

# Ref https://wimonitor:ki.hyprland.org/Configuring/Workspace-Rules/
# "Smart gaps" /monitor: "No gaps when only"
# uncomment all if you wish to use that.
workspace = w[tv1], gapsout:10, gapsin:5
workspace = f[1], gapsout:0, gapsin:0
windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
windowrulev2 = rounding 0, floating:0, onworkspace:f[1]
windowrulev2 = size 600 200,floating:1

